#!/bin/bash
# Generate wireguard keys.
WG=/usr/bin/wg
TEE=/usr/bin/tee

if [ -z "$1" ]; then
    echo "Requires name for output files."
    exit 1
else
    name=$1
fi

${WG} genkey | ${TEE} "${1}.key" | ${WG} pubkey > "${1}.pub"
chmod 0400 "${1}.{key,pub}"
