---
# yamllint disable rule:line-length
###############################################################################
# Configure Wireguard Connections
###############################################################################
# Uses sysctl (e.g. the kernel namespace must be available).

- name: 'Config | force remove'
  when: wireguard_service_force_refresh_adapters
  block:
    - name: 'Config | force remove | find existing adapter configs'
      ansible.builtin.find:
        paths: '/etc/wireguard'
        patterns: '*.conf'
      register: _wireguard_adapter_configs

    - name: 'Config | force remove | remove'
      ansible.builtin.include_tasks: 'remove.yml'
      vars:
        path: '{{ item.path }}'
      loop: '{{ _wireguard_adapter_configs.files }}'
      loop_control:
        label: '{{ item.path | basename }}'

- name: 'Config | set IP forwarding'
  when: not wireguard_container_enable
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: true
  loop:
    - {name: 'net.ipv4.conf.all.forwarding', value: '{{ wireguard_service_ipv4_forwarding_enable | int }}'}
    - {name: 'net.ipv4.conf.default.forwarding', value: '{{ wireguard_service_ipv4_forwarding_enable | bool | int }}'}
    - {name: 'net.ipv6.conf.all.forwarding', value: '{{ wireguard_service_ipv6_forwarding_enable | int }}'}
    - {name: 'net.ipv6.conf.default.forwarding', value: '{{ wireguard_service_ipv6_forwarding_enable | bool | int }}'}

- name: 'Config | configure wireguard adapters'
  ansible.builtin.include_tasks: 'adapter.yml'
  loop: '{{ wireguard_adapters }}'
  loop_control:
    loop_var: adapter
    label: '{{ adapter.name }}'
  no_log: true  # wg private key
