---
###############################################################################
# Configure Wireguard Connections
###############################################################################
# Uses sysctl (e.g. kernel namespace must be available).

- name: '{{ "Config | filesystem | query " ~ wireguard___app._etc_dir }}'
  when: wireguard_srv_force_refresh_adapters
  ansible.builtin.find:
    paths: '{{ wireguard___app._etc_dir }}'
    patterns: '*.conf'
  register: wireguard__adapter_configs

- name: 'Config | remove'
  when: wireguard_srv_force_refresh_adapters
  ansible.builtin.include_tasks: 'remove.yml'
  vars:
    path: '{{ item.path }}'
    adapter: '{{ item.path | basename | splitext | first }}'
  loop: '{{ wireguard__adapter_configs.files }}'
  loop_control:
    label: '{{ item.path | basename }}'

- name: 'Config | sysctl | set IP forwarding'
  when: not wireguard_flg_container
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: true
  loop:
    - name: 'net.ipv4.conf.all.forwarding'
      value: '{{ wireguard__srv._ipv4_forwarding | int }}'
    - name: 'net.ipv4.conf.default.forwarding'
      value: '{{ wireguard__srv._ipv4_forwarding | bool | int }}'
    - name: 'net.ipv6.conf.all.forwarding'
      value: '{{ wireguard__srv._ipv6_forwarding | int }}'
    - name: 'net.ipv6.conf.default.forwarding'
      value: '{{ wireguard__srv._ipv6_forwarding | bool | int }}'

- name: 'Config | adapter'
  ansible.builtin.include_tasks: 'adapter.yml'
  loop: '{{ wireguard_cfg_adapters }}'
  loop_control:
    loop_var: 'adapter'
    label: '{{ adapter.name }}'
  no_log: true  # WG private key.
