---
###############################################################################
# Enable wireguard in Kernel Init for Dropbear over Wireguard Support
###############################################################################
# Reference:
# * https://github.com/r-pufky/wireguard-initramfs

- name: '{{ "InitRAMFS | filesystem | set " ~ wireguard___initramfs._cfg }}'
  notify: 'Handlers | update | wireguard'
  ansible.builtin.template:
    src: 'initramfs.j2'
    dest: '{{ wireguard___initramfs._cfg }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true
