---
# yamllint disable rule:line-length
###############################################################################
# Wireguard Install
###############################################################################
# Kernels at 5.6 or newer do not require kernel modules to be installed. LXC
# containers need to be built specifically against PVE node headers. PVE
# cluster nodes need to have PVE headers installed.
#
# Args:
#   _wireguard_is_pve: ansible.builtin.stat - stat.exists if PVE node.
#
# Reference:
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#add-wireguard-kernel-support
# * https://nixvsevil.com/posts/wireguard-in-proxmox-lxc/
# yamllint enable rule:line-length

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ wireguard_role_packages }}'
      - '{{
          wireguard_role_initramfs_packages
          if wireguard_initramfs_enable else
          []
        }}'
    apt_package_update_cache: true

# TODO(role): Update for PVE8.x and enable.
# - name: 'Install | PVE'
#   when: _wireguard_is_pve.stat.exists
#   block:
#     - name: 'Install | PVE | set wireguard kernel modules'
#       ansible.builtin.copy:
#         src: 'etc/modules-load.d/wireguard.conf'
#         dest: '/etc/modules-load.d/wireguard.conf'
#         owner: 'root'
#         group: 'root'
#         mode: '0644'
#         force: true
#
#     - name: 'Install | PVE | load wireguard kernel module realtime'
#       community.general.modprobe:
#         name: 'wireguard'
#         state: 'present'
#       failed_when: false
#       changed_when: false

- name: 'Install | wireguard-initramfs'
  when: wireguard_initramfs_enable
  block:
    - name: 'Install | wireguard-initramfs | {{ wireguard_initramfs_version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.repo'
      vars:
        repo_release_owner: '{{ wireguard_role_repo_release_owner }}'
        repo_release_repo: '{{ wireguard_role_repo_release_repo }}'
        repo_release_tag: '{{ wireguard_initramfs_version }}'
        repo_release_asset: '{{ wireguard_role_repo_release_asset }}'
        repo_extract_dir: '{{ wireguard_role_repo_extract_dir }}'
        repo_extract_symlink: '{{ wireguard_role_repo_extract_symlink }}'
        repo_extract_mode: 'a-st,o-rwx'
        repo_extract_extra_opts: '--strip-components=1'

    - name: 'Install | wireguard-initramfs | make'
      when: _repo_changed
      ansible.builtin.command: 'make install'
      become: true
      args:
        chdir: '/opt/wireguard-initramfs/wireguard-initramfs'
      changed_when: true
