---
###############################################################################
# Wireguard installation for VM or Physical Machine (Kernel > 5.6)
###############################################################################
# Kernels at 5.6 or newer do not require kernel modules to be installed.
#
# Reference:
# * https://r-pufky.github.io/docs/services/wireguard/linux-setup.html#service-wireguard-linux-setup

- name: 'post 5.6 kernel | install kernel headers'
  ansible.builtin.apt:
    name:  'linux-headers-amd64'
    state: 'latest'
    update_cache: true

- name: 'post 5.6 kernel | install wireguard'
  ansible.builtin.apt:
    name:  '{{ wireguard_default_packages }}'
    state: 'latest'
    update_cache: true
    install_recommends: true
