---
###############################################################################
# Wireguard Install
###############################################################################
# Manually download, extract, build, and install packages accordingly to Linux
# FHS standards:
#
# Type    | Perms               | Path
# --------|---------------------|-------
# Source  | 0755/0644 root:root | /opt/*

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ wireguard___packages }}'
      - '{{
          wireguard___initramfs_packages if wireguard_flg_initramfs else []
        }}'
    apt_srv_package_update_cache: true

###############################################################################
# wireguard-initramfs
###############################################################################

- name: 'Install | wireguard-initramfs'
  when: wireguard_flg_initramfs
  block:
    # src_dir includes opt_dir.
    - name: 'Install | filesystem | set system directories'
      ansible.builtin.file:
        path: '{{ wireguard___initramfs._src_d }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'Install | filesystem | find previous installations'
      ansible.builtin.find:
        paths: '{{ wireguard___initramfs._src_d }}'
        file_type: 'directory'
        recurse: false
        excludes:
          - '{{ wireguard___release._initramfs }}'
      register: wireguard__cmd

    - name: 'Install | filesystem | remove previous installations'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ wireguard__cmd.files }}'
      loop_control:
        label: '{{ item.path }}'

    - name: 'Install | filesystem | stage wireguard-initramfs'
      when: not (molecule_flg_inject | default(false))
      ansible.builtin.get_url:
        url: '{{ wireguard___initramfs._url }}'
        dest: '{{ "/tmp/" ~ wireguard___initramfs._package }}'
        force: false
        owner: 'root'
        group: 'root'
        mode: '0644'
        headers:
          Authorization: '{{ wireguard__srv._token | default(omit) }}'
      register: wireguard__cmd
      until: wireguard__cmd is succeeded

    - name:
        '{{ "Install | filesystem | set " ~ wireguard___initramfs._live_d }}'
      ansible.builtin.file:
        path: '{{ wireguard___initramfs._live_d }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'Install | filesystem | unpack wireguard-initramfs'
      ansible.builtin.unarchive:
        creates: '{{ wireguard___initramfs._live_d ~ "/Makefile" }}'
        src: '{{ "/tmp/" ~ wireguard___initramfs._package }}'
        remote_src: true
        dest: '{{ wireguard___initramfs._live_d }}'
        owner: 'root'
        group: 'root'
        mode: 'a-st'
        extra_opts: ['--strip-components=1']
      register: wireguard__cmd

    - name: 'Install | build | 🗘 wireguard-initramfs (<1 minute) 🗘'
      when: wireguard__cmd.changed  # noqa: no-handler immediate.
      ansible.builtin.debug:
        msg: 'Building wireguard-initramfs (<1 minute).'

    - name: '{{
          "Install | build | wireguard-initramfs " ~
          wireguard___initramfs._version
        }}'
      when: wireguard__cmd.changed  # noqa: no-handler immediate.
      ansible.builtin.command: 'make install'
      become: true
      args:
        chdir: '{{ wireguard___initramfs._live_d }}'
      changed_when: true
