---
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'
- name: 'Install'
  ansible.builtin.import_tasks: 'install.yml'
- name: 'Config'
  ansible.builtin.import_tasks: 'config.yml'

- name: 'InitRAMFS'
  when: wireguard_flg_initramfs
  ansible.builtin.import_tasks: 'initramfs.yml'
