---
###############################################################################
# Wireguard Prep
###############################################################################
#
# Generates:
#   _wireguard_pve: ansible.builtin.stat - stat.exists if PVE node.
#
# Reference:
# *

- name: 'Prep | assert kernel version 5.6+'
  ansible.builtin.assert:
    that:
      - ansible_kernel is version("5.6", ">")
    fail_msg: 'Only kernel versions 5.6+ are supported.'

- name: 'Prep | query for PVE'
  ansible.builtin.stat:
    path: '/usr/bin/pveversion'
  register: _wireguard_is_pve

- name: 'Prep | assert not PVE'
  ansible.builtin.assert:
    that:
      - not _wireguard_is_pve.stat.exists
    fail_msg: 'PVE cluster node deployments are currently disabled.'
