---
###############################################################################
# Remove Interface
###############################################################################
# Stop interface and remove configuration file. If the adapter is not currently
# running an error will be raised stopping a non-running adapter - ignore.
#
# Args:
#   path: str - Absolute path to the adapter configuration file.
#   adapter: str - Parsed adapter name.

- name: '{{ "Remove | wg | stop " ~ adapter }}'
  ansible.builtin.command: '{{ "wg-quick down " ~ adapter }}'
  changed_when: false
  failed_when: false

- name: '{{ "Remove | filesystem | remove " ~ path }}'
  ansible.builtin.file:
    path: '{{ path }}'
    state: 'absent'
