---
###############################################################################
# Enable wireguard in Kernel Init for Dropbear over Wireguard Support
###############################################################################
#
# Reference:
# * https://github.com/r-pufky/wireguard-initramfs

- name: 'adapter | ensure latest initramfs version'
  ansible.builtin.apt:
    name:  'initramfs-tools'
    state: 'latest'
    update_cache: true

- name: 'adapter | create /etc/wireguard-initramfs'
  ansible.builtin.file:
    path:  '/etc/wireguard-initramfs'
    owner: 'root'
    group: 'root'
    state: 'directory'
    mode:  0755

- name: 'adapter | set wireguard-initramfs config'
  ansible.builtin.template:
    src:   'wireguard-initramfs/config.j2'
    dest:  '/etc/wireguard-initramfs/config'
    owner: 'root'
    group: 'root'
    mode:  0644
    force: true
  notify: 'update-initramfs wireguard'

- name: 'adapter | set wireguard boot client private key'
  ansible.builtin.copy:
    dest:  '/etc/wireguard-initramfs/private_key'
    owner: 'root'
    group: 'root'
    mode:  0400
    content: '{{ wireguard_boot_client_private_key }}'
  notify: 'update-initramfs wireguard'

- name: 'adapter | set wireguard-initramfs hooks'
  ansible.builtin.copy:
    src:   'wireguard-initramfs/hooks'
    dest:  '/etc/initramfs-tools/hooks/wireguard'
    owner: 'root'
    group: 'root'
    mode:  0755
  notify: 'update-initramfs wireguard'

- name: 'adapter | set wireguard-initramfs premount'
  ansible.builtin.copy:
    src:   'wireguard-initramfs/init-premount'
    dest:  '/etc/initramfs-tools/scripts/init-premount/wireguard'
    owner: 'root'
    group: 'root'
    mode:  0755
  notify: 'update-initramfs wireguard'

- name: 'adapter | set wireguard-initramfs bottom'
  ansible.builtin.copy:
    src:   'wireguard-initramfs/init-bottom'
    dest:  '/etc/initramfs-tools/scripts/init-bottom/wireguard'
    owner: 'root'
    group: 'root'
    mode:  0755
  notify: 'update-initramfs wireguard'
