---
collections:
  # https://docs.ansible.com/ansible/latest/collections/ansible/posix/index.html
  # sysctl synchronize, authorized_key
  - ansible.posix
  # https://docs.ansible.com/ansible/latest/collections/community/general/
  # archive
  - community.general

roles: []