---
# yamllint disable rule:line-length
collections:
  - name: 'ansible.posix'  # https://docs.ansible.com/ansible/latest/collections/ansible/posix/index.html

roles:
  - name: 'r_pufky.srv.apt'  # https://github.com/r-pufky/ansible_collection_srv
  - name: 'r_pufky.srv.github'  # https://github.com/r-pufky/ansible_collection_srv
