---
###############################################################################
# Wireguard Handlers
###############################################################################

- name: 'Handlers | update-initramfs'
  ansible.builtin.command: 'update-initramfs -u'
  changed_when: true

- name: 'Handlers | update-grub'
  ansible.builtin.command: 'update-grub'
  changed_when: true
