---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | import | role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | cache'

    - name: '{{ "Prepare | cache | " ~ wireguard___initramfs._package }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{ "Prepare | cache | " ~ wireguard___initramfs._package }}'
        test_dest: '{{ wireguard___initramfs._package }}'
        test_url: '{{ wireguard___initramfs._url }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Prepare | import | role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Prepare | inject | " ~ wireguard___initramfs._package }}'
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/" ~
            wireguard___initramfs._package
          }}'
        dest: '{{ "/tmp/" ~ wireguard___initramfs._package }}'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: '{{ "Prepare | filesystem | create " ~ wireguard___app._etc_dir }}'
      ansible.builtin.file:
        path: '{{ wireguard___app._etc_dir }}'
        owner: 'root'
        group: 'root'
        mode: '0700'
        state: 'directory'

    - name: '{{
          "Prepare | inject | " ~ wireguard___app._etc_dir ~
          "/example_disabled.conf"
        }}'
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/adapter.conf"
          }}'
        dest: '{{ wireguard___app._etc_dir ~ "/example_disabled.conf" }}'
        owner: 'root'
        group: 'root'
        mode: '0600'

    - name: '{{
          "Prepare | inject | " ~ wireguard___app._etc_dir ~
          "/example_absent.conf"
        }}'
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/adapter.conf"
          }}'
        dest: '{{ wireguard___app._etc_dir ~ "/example_absent.conf" }}'
        owner: 'root'
        group: 'root'
        mode: '0600'
