---
- name: 'Converge'
  hosts: 'all'
  gather_facts: true  # ansible_kernel
  tasks:
    - name: 'Converge | apply r_pufky.deb.wireguard'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.wireguard'
