---
###############################################################################
# Force Refresh
###############################################################################
# Adapters can be force removed and re-created.
#
# Tests:
# * force refreshing adapters removes and re-creates adapters without failing.
# * Wireguard deploys successfully within containers when enabled.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        deb_flg_container: true  # Tests wireguard_flg_container as well.
        wireguard_srv_force_refresh_adapters: true
        wireguard_cfg_adapters:
          - name: 'example_present'
            state: 'present'
            private_key: 'iMgmYiJ5KykymUlWO/qtaC1azuFqH3zKSxs+dEgDRmI='
            address:
              - '172.31.255.10/24'
            save_config: false
            peers:
              - public_key: 'gyW39I9bAiOBXyhL8LWw9qwiTZgMmtAbsWtLUv8uKTc='
                preshared_key: 'xZOa9wXPCL86UtIEMc4kKwj/wsCohs+S9NexPLDaFwU='
                allowed_ips:
                  - '172.31.255.254/32'
                endpoint:
                  host: '127.0.0.1'
                  port: 51820
                persistent_keepalive: 25
platforms:
  - name: 'wireguard-force-refresh'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
