---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | example_present.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | example_present.conf'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/adapter.conf"
          }}'
        test_file: '/etc/wireguard/example_present.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0600'
        test_diff: true
